more complicated than that !

diff --git a/.openshift/action_hooks/pre_build b/.openshift/action_hooks/pre_build
--- a/.openshift/action_hooks/pre_build
+++ b/.openshift/action_hooks/pre_build
@@ -46,11 +46,11 @@ else
 	fi
 
 	#verify that the desired version installed successfully
-	if [[ ! `${PLAY_FULL_PATH}play version | tail -1` = $VERSION ]]; then
-		echo "Error installing play $VERSION to $PLAY_FULL_PATH with ${PLAY_FULL_PATH}play version"
-		rm -fr $PLAY_FULL_PATH
-		exit 1
-	fi
+	#if [[ ! `${PLAY_FULL_PATH}play version | tail -1` = $VERSION ]]; then
+	#	echo "Error installing play $VERSION to $PLAY_FULL_PATH with ${PLAY_FULL_PATH}play version"
+	#	rm -fr $PLAY_FULL_PATH
+	#	exit 1
+	#fi
 
 	#cleanup, remove other play versions
 	for old in [play-]*; do 
