change deploy way on typesafe

diff --git a/.openshift/action_hooks/start b/.openshift/action_hooks/start
--- a/.openshift/action_hooks/start
+++ b/.openshift/action_hooks/start
@@ -3,47 +3,53 @@
 # script. The application will work only if it binds to
 # $OPENSHIFT_INTERNAL_IP:8080
 
-# set env api keys
-source ${OPENSHIFT_DATA_DIR}/my-social.conf
+# debug
+# set -x
 
-# loads $PLAY_PARAMS
+#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
 . ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config
 
 if [[ ! $? -eq 0 ]]; then
-  exit $?
+	exit $?
 fi
 
-LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"
+if [[ ! -f $PLAY_COMMAND ]]; then
+	echo "Error: couldn't find play executable at $PLAY_COMMAND"
+	exit 1
+fi
 
-chmod +x ${OPENSHIFT_REPO_DIR}target/start
+## stop play application
+${OPENSHIFT_REPO_DIR}.openshift/action_hooks/stop
 
-APP_COMMAND="${OPENSHIFT_REPO_DIR}target/start $PLAY_PARAMS "\
-"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
-"-Dhttp.address=${OPENSHIFT_DIY_IP} "\
-"-Dmongodb.uri=\"${OPENSHIFT_MONGODB_DB_URL}${OPENSHIFT_GEAR_NAME}\" "\
-"-Dsocial.betaseries.secret=\"${BETASERIES_SECRET}\" "\
-"-Dsocial.twitter.clientId=\"${TWITTER_CLIENTID}\" "\
-"-Dsocial.twitter.secret=\"${TWITTER_SECRET}\" "\
-"-Dsocial.scoopit.clientId=\"${SCOOPIT_CLIENTID}\" "\
-"-Dsocial.scoopit.secret=\"${SCOOPIT_SECRET}\" "\
-"-Dsocial.facebook.clientId=\"${FACEBOOK_CLIENTID}\" "\
-"-Dsocial.facebook.secret=\"${FACEBOOK_SECRET}\" "\
-"-Dsocial.googleplus.clientId=\"${GOOGLEPLUS_CLIENTID}\" "\
-"-Dsocial.googleplus.secret=\"${GOOGLEPLUS_SECRET}\" "\
-"-Dsocial.viadeo.clientId=\"${VIADEO_CLIENTID}\" "\
-"-Dsocial.viadeo.secret=\"${VIADEO_SECRET}\" "\
-"-Dsocial.linkedin.clientId=\"${LINKEDIN_CLIENTID}\" "\
-"-Dsocial.linkedin.secret=\"${LINKEDIN_SECRET}\" "\
-"-Dsocial.github.clientId=\"${GITHUB_CLIENTID}\" "\
-"-Dsocial.github.secret=\"${GITHUB_SECRET}\" "\
-"-Dsocial.stackexchange.clientId=\"${STACKEXCHANGE_CLIENTID}\" "\
-"-Dsocial.stackexchange.secret=\"${STACKEXCHANGE_SECRET}\" "\
-"-Dsocial.stackexchange.key=\"${STACKEXCHANGE_KEY}\" "\
-"-Dsocial.trello.clientId=\"${TRELLO_CLIENTID}\" "\
-"-Dsocial.trello.secret=\"${TRELLO_SECRET}\" "\
-"-Dsocial.bitbucket.clientId=\"${BITBUCKET_CLIENTID}\" "\
-"-Dsocial.bitbucket.secret=\"${BITBUCKET_SECRET}\" "\
-"-Dconfig.resource=openshift.conf"
+if [[ ! $? -eq 0 ]]; then
+	echo "Error: could not stop play application"
+	exit 1
+fi
 
-echo $APP_COMMAND &>> $LOG_FILE
-nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
+cd "$OPENSHIFT_REPO_DIR"
+
+# clean everything
+echo "$PLAY_COMMAND clean" >> $LOG_FILE
+$PLAY_COMMAND clean &> $LOG_FILE
+
+echo "$PLAY_COMMAND deps $DEPS_PARAMS -Divy.home=${OPENSHIFT_TMP_DIR}ivy2/" >> $LOG_FILE
+$PLAY_COMMAND deps $DEPS_PARAMS -Divy.home=${OPENSHIFT_TMP_DIR}ivy2/ &> $LOG_FILE
+
+if [[ ! $? -eq 0 ]]; then
+	echo "Error: could not update dependencies"
+	echo "Error executing '$PLAY_COMMAND $DEPS_PARAMS'"
+	exit 1
+fi
+
+
+export PLAY_LOG_PATH=${OPENSHIFT_DIY_LOG_DIR}
+echo "$PLAY_COMMAND start --%$ID $PLAY_PARAMS" >> $LOG_FILE
+nohup bash -c "$PLAY_COMMAND start --%$ID $PLAY_PARAMS -Duser.timezone=Europe/London &> $LOG_FILE" &> /dev/null &
+
+if [[ ! $? -eq 0 ]]; then
+	echo "Error: starting play application"
+	echo "Error executing '$APP_COMMAND'"
+	exit 1
+fi
+
+exit 0
diff --git a/.openshift/action_hooks/stop b/.openshift/action_hooks/stop
--- a/.openshift/action_hooks/stop
+++ b/.openshift/action_hooks/stop
@@ -1,66 +1,64 @@
 #!/bin/bash
 # The logic to stop your application should be put in this script.
 
-# debug 
+# debug
 # set -x
 
-LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"
-
-function kill_app {
-	COMMAND="$1"
-	# try 5 times to kill it
-	for c in `seq 1 5`; do
-		echo "Trying to kill proccess, attempt number $c" >> $LOG_FILE
-		echo "$COMMAND" >> $LOG_FILE
-		bash -c "$COMMAND &>> $LOG_FILE 2>&1" &> /dev/null
-		sleep $c
-		#killed it
-		if [[ -z `ps -A | grep ' java$'` ]]; then
-			if [[ -f "RUNNING_PID" ]]; then
-				rm RUNNING_PID
-			fi
-			popd > /dev/null
-			exit 0
-		fi
-	done
-}
+#loads VERSION, DEPS_PARAMS, ID, LOG_FILE, PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"
+. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config
 
 if [[ ! $? -eq 0 ]]; then
 	exit $?
 fi
 
-pushd "$OPENSHIFT_REPO_DIR" > /dev/null
-
 #kill play if it was running
-if [[ -f "RUNNING_PID" ]]; then
+if [[ -f "server.pid" ]]; then
 
-	pid=`cat RUNNING_PID`
-	echo "Stopping play application" >> $LOG_FILE
+	if [[ ! -f $PLAY_COMMAND ]]; then
+		echo "Error: couldn't find play executable at $PLAY_COMMAND"
+		exit 1
+	fi
 
-	if [[ -n $pid ]]; then
-		#try to kill it nicely
-		kill_app "kill -SIGTERM $pid"
-		#try to kill it harshly
-		kill_app "kill -SIGKILL $pid"
+	echo "Stopping play application"
+	bash -c "$PLAY_COMMAND stop &> $LOG_FILE" &> /dev/null
+
+	#manually remove server.pid if it's there
+	if [[ -f "server.pid" ]]; then
+		echo "Manually removing server.pid file"
+		bash -c "rm server.pid &> $LOG_FILE" &> /dev/null
 	fi
 fi
 
-#it survived, try to kill java
-if [[ -n `ps -A | grep java` ]]; then
-	echo "Stopping java proccess" >> $LOG_FILE
-	#try to kill it nicely
-	kill_app "pkill -SIGTERM java"
-	#try to kill it harshly
-	kill_app "pkill -SIGKILL java"
+#it survived, try to kill it manually
+if [[ -n `ps -A | grep ' java$'` ]]; then
+
+	# try 5 times to kill it
+	for c in `seq 1 5`; do
+		echo "Trying to kill java proccess, attemp number $c"
+		bash -c "pkill java &> $LOG_FILE" &> /dev/null
+		sleep $c
+		#killed it
+		if [[ -z `ps -A | grep ' java$'` ]]; then
+			exit 0
+		fi
+	done
+
+	# try 5 times to kill it
+	for c in `seq 1 5`; do
+		echo "Trying to kill java proccess with -SIGKILL, attemp number $c"
+		bash -c "pkill -SIGKILL java &> $LOG_FILE" &> /dev/null
+		sleep $c
+		#killed it
+		if [[ -z `ps -A | grep ' java$'` ]]; then
+			exit 0
+		fi
+	done
+
+	#couldn't kill it
+	if [[ -n `ps -A | grep ' java$'` ]]; then
+		echo "Error: could not stop play application, error executing 'pkill java'"
+		exit 1
+	fi
 fi
 
-#couldn't kill it
-if [[ -n `ps -A | grep java` ]]; then
-	echo "Error: could not stop play application, error executing 'pkill java'" >> $LOG_FILE
-	popd
-	exit 1
-fi
-
-popd > /dev/null
 exit 0
-
